
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.Date;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;


public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    private static Connection connection;
    private static PreparedStatement Clear;
    
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        MainLabel = new javax.swing.JLabel();
        AddDatePanel = new javax.swing.JTabbedPane();
        AddFacultyPanel = new javax.swing.JPanel();
        FacultyNameLabel = new javax.swing.JLabel();
        addFacultyNameTextField = new javax.swing.JTextField();
        AddFacultyButton = new javax.swing.JButton();
        AddFacultyFeedbackLabel = new javax.swing.JLabel();
        FacultyListLabel = new javax.swing.JLabel();
        ListFacultyScrollPane = new javax.swing.JScrollPane();
        ListFacTextArea = new javax.swing.JTextArea(DataTypeTools.ALtoPrintableString(Faculty.getFacultyList()));
        RoomEntryPanel = new javax.swing.JPanel();
        AddRoomLabel = new javax.swing.JLabel();
        RoomNameTextField = new javax.swing.JTextField();
        SeatNumberTextField = new javax.swing.JTextField();
        AddRoomButton = new javax.swing.JButton();
        AddRoomFeedbackLabel = new javax.swing.JLabel();
        AllRoomsLabel = new javax.swing.JLabel();
        GetRoomsScrollPane = new javax.swing.JScrollPane();
        GetRoomsTextArea = new javax.swing.JTextArea(DataTypeTools.ALtoPrintableString(RoomEntry.getAllRooms()));
        DeleteRoomLabel = new javax.swing.JLabel();
        DeleteRoomComboBox = new javax.swing.JComboBox<>();
        DeleteRoomButton = new javax.swing.JButton();
        AddDatesPanel = new javax.swing.JPanel();
        AddDatesJLabel = new javax.swing.JLabel();
        AddDatesYearTextField = new javax.swing.JTextField();
        AddDatesButton = new javax.swing.JButton();
        AddDatesFeedbackLabel = new javax.swing.JLabel();
        AddDatesMonthTextField = new javax.swing.JTextField();
        AddDatesDaysTextField = new javax.swing.JTextField();
        DatesYearLabel = new javax.swing.JLabel();
        DatesMonthLabel = new javax.swing.JLabel();
        DatesDayLabel = new javax.swing.JLabel();
        AllDatesLabel = new javax.swing.JLabel();
        ShowAllDatesScrolllPane = new javax.swing.JScrollPane();
        ShowAllDatesTextArea = new javax.swing.JTextArea(Dates.AllDatesListString());
        ReservationPanel = new javax.swing.JPanel();
        MakeReservationLabel = new javax.swing.JLabel();
        FacultyComboBox = new javax.swing.JComboBox<>();
        DateComboBox = new javax.swing.JComboBox<>();
        MakeReservationButton = new javax.swing.JButton();
        ResFeedbackLabel = new javax.swing.JLabel();
        ReservationScrollPane = new javax.swing.JScrollPane();
        ReservationTextArea = new javax.swing.JTextArea();
        ReservationSeatsTextField = new javax.swing.JTextField();
        ReservationsbyFacComboBox = new javax.swing.JComboBox<>();
        ReservationsbyFacButton = new javax.swing.JButton();
        ReservationbyFacLabel = new javax.swing.JLabel();
        ReservationsbyDateSearchLabel = new javax.swing.JLabel();
        ReservationsbyDateComboBox = new javax.swing.JComboBox<>();
        ReservationsbyDateButton = new javax.swing.JButton();
        MakeResFacLabel = new javax.swing.JLabel();
        MakeResDateLabel = new javax.swing.JLabel();
        MakeResAddSeatsLAbel = new javax.swing.JLabel();
        ClearDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MainLabel.setFont(new java.awt.Font("Cooper Black", 0, 34)); // NOI18N
        MainLabel.setForeground(new java.awt.Color(255, 0, 0));
        MainLabel.setText("Room Scheduler");

        AddDatePanel.setName(""); // NOI18N

        AddFacultyPanel.setName(""); // NOI18N

        FacultyNameLabel.setText("Faculty Name");

        addFacultyNameTextField.setColumns(20);

        AddFacultyButton.setText("Submit");
        AddFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFacultyButtonActionPerformed(evt);
            }
        });

        AddFacultyFeedbackLabel.setText(" ");

        FacultyListLabel.setText("Faculty List");

        ListFacTextArea.setColumns(20);
        ListFacTextArea.setRows(5);
        ListFacultyScrollPane.setViewportView(ListFacTextArea);

        javax.swing.GroupLayout AddFacultyPanelLayout = new javax.swing.GroupLayout(AddFacultyPanel);
        AddFacultyPanel.setLayout(AddFacultyPanelLayout);
        AddFacultyPanelLayout.setHorizontalGroup(
            AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                .addGroup(AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(AddFacultyButton))
                    .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddFacultyFeedbackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                                    .addComponent(FacultyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(32, 32, 32)
                                    .addComponent(addFacultyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                                .addComponent(FacultyListLabel)
                                .addGap(35, 35, 35)
                                .addComponent(ListFacultyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        AddFacultyPanelLayout.setVerticalGroup(
            AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFacultyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddFacultyButton)
                .addGap(18, 18, 18)
                .addComponent(AddFacultyFeedbackLabel)
                .addGap(67, 67, 67)
                .addGroup(AddFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddFacultyPanelLayout.createSequentialGroup()
                        .addComponent(FacultyListLabel)
                        .addGap(0, 219, Short.MAX_VALUE))
                    .addComponent(ListFacultyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap())
        );

        AddDatePanel.addTab("Add Faculty", AddFacultyPanel);

        AddRoomLabel.setText("Add Room (Room Name, Number of Seats)");

        RoomNameTextField.setColumns(20);

        SeatNumberTextField.setColumns(20);

        AddRoomButton.setText("Submit");
        AddRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomButtonActionPerformed(evt);
            }
        });

        AllRoomsLabel.setText("Get Rooms");

        GetRoomsTextArea.setColumns(20);
        GetRoomsTextArea.setRows(5);
        GetRoomsScrollPane.setViewportView(GetRoomsTextArea);

        DeleteRoomLabel.setText("Delete Room");

        DeleteRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(RoomEntry.getRoomStringArray()));

        DeleteRoomButton.setText("Submit");
        DeleteRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoomEntryPanelLayout = new javax.swing.GroupLayout(RoomEntryPanel);
        RoomEntryPanel.setLayout(RoomEntryPanelLayout);
        RoomEntryPanelLayout.setHorizontalGroup(
            RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AllRoomsLabel)
                .addGap(37, 37, 37)
                .addComponent(GetRoomsScrollPane)
                .addContainerGap())
            .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddRoomFeedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                        .addComponent(DeleteRoomLabel)
                        .addGap(86, 86, 86)
                        .addComponent(DeleteRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(DeleteRoomButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddRoomLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(RoomNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(SeatNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomEntryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddRoomButton)
                .addGap(178, 178, 178))
        );
        RoomEntryPanelLayout.setVerticalGroup(
            RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddRoomLabel)
                    .addGroup(RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoomNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SeatNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddRoomButton)
                .addGap(4, 4, 4)
                .addComponent(AddRoomFeedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRoomLabel)
                    .addComponent(DeleteRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteRoomButton))
                .addGap(34, 34, 34)
                .addGroup(RoomEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomEntryPanelLayout.createSequentialGroup()
                        .addComponent(AllRoomsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(GetRoomsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap())
        );

        AddDatePanel.addTab("Room Entry", RoomEntryPanel);

        AddDatesJLabel.setText("Add Dates");

        AddDatesYearTextField.setColumns(8);

        AddDatesButton.setText("Submit");
        AddDatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDatesButtonActionPerformed(evt);
            }
        });

        AddDatesMonthTextField.setColumns(4);

        AddDatesDaysTextField.setColumns(4);

        DatesYearLabel.setText("Year");

        DatesMonthLabel.setText("Month");

        DatesDayLabel.setText("Day");

        AllDatesLabel.setText("All Possible Dates");

        ShowAllDatesTextArea.setColumns(20);
        ShowAllDatesTextArea.setRows(5);
        ShowAllDatesScrolllPane.setViewportView(ShowAllDatesTextArea);

        javax.swing.GroupLayout AddDatesPanelLayout = new javax.swing.GroupLayout(AddDatesPanel);
        AddDatesPanel.setLayout(AddDatesPanelLayout);
        AddDatesPanelLayout.setHorizontalGroup(
            AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDatesPanelLayout.createSequentialGroup()
                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDatesPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(AddDatesButton))
                    .addGroup(AddDatesPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddDatesFeedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddDatesPanelLayout.createSequentialGroup()
                                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddDatesPanelLayout.createSequentialGroup()
                                        .addComponent(AddDatesJLabel)
                                        .addGap(91, 91, 91)
                                        .addComponent(AddDatesYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddDatesPanelLayout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(DatesYearLabel)))
                                .addGap(42, 42, 42)
                                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddDatesMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatesMonthLabel))
                                .addGap(47, 47, 47)
                                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DatesDayLabel)
                                    .addComponent(AddDatesDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddDatesPanelLayout.createSequentialGroup()
                                .addComponent(AllDatesLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ShowAllDatesScrolllPane, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        AddDatesPanelLayout.setVerticalGroup(
            AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDatesPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatesYearLabel)
                    .addComponent(DatesMonthLabel)
                    .addComponent(DatesDayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDatesJLabel)
                    .addComponent(AddDatesYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDatesMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDatesDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddDatesButton)
                .addGap(26, 26, 26)
                .addComponent(AddDatesFeedbackLabel)
                .addGap(72, 72, 72)
                .addGroup(AddDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDatesPanelLayout.createSequentialGroup()
                        .addComponent(AllDatesLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ShowAllDatesScrolllPane, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );

        AddDatePanel.addTab("Add Dates", AddDatesPanel);

        MakeReservationLabel.setText("Make Reservation:");

        FacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));
        FacultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyComboBoxActionPerformed(evt);
            }
        });

        DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));

        MakeReservationButton.setText("Submit");
        MakeReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeReservationButtonActionPerformed(evt);
            }
        });

        ReservationTextArea.setColumns(20);
        ReservationTextArea.setRows(5);
        ReservationScrollPane.setViewportView(ReservationTextArea);

        ReservationSeatsTextField.setColumns(10);
        ReservationSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationSeatsTextFieldActionPerformed(evt);
            }
        });

        ReservationsbyFacComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));

        ReservationsbyFacButton.setText("Search");
        ReservationsbyFacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationsbyFacButtonActionPerformed(evt);
            }
        });

        ReservationbyFacLabel.setText("Reservations by Faculty Search");

        ReservationsbyDateSearchLabel.setText("Reservations by Date Search");

        ReservationsbyDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));

        ReservationsbyDateButton.setText("Search");
        ReservationsbyDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationsbyDateButtonActionPerformed(evt);
            }
        });

        MakeResFacLabel.setText("Faculty:");

        MakeResDateLabel.setText("Dates:");

        MakeResAddSeatsLAbel.setText("Add Seats:");

        javax.swing.GroupLayout ReservationPanelLayout = new javax.swing.GroupLayout(ReservationPanel);
        ReservationPanel.setLayout(ReservationPanelLayout);
        ReservationPanelLayout.setHorizontalGroup(
            ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                        .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservationPanelLayout.createSequentialGroup()
                                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                                        .addComponent(ReservationsbyFacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ReservationsbyFacButton))
                                    .addComponent(ReservationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResFeedbackLabel))
                            .addComponent(MakeReservationLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                        .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReservationbyFacLabel)
                            .addComponent(MakeResFacLabel))
                        .addGap(52, 52, 52)
                        .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReservationPanelLayout.createSequentialGroup()
                                .addComponent(MakeResDateLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ReservationPanelLayout.createSequentialGroup()
                                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReservationsbyDateSearchLabel)
                                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                                        .addComponent(ReservationsbyDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ReservationsbyDateButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MakeResAddSeatsLAbel)
                            .addGroup(ReservationPanelLayout.createSequentialGroup()
                                .addComponent(ReservationSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MakeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        ReservationPanelLayout.setVerticalGroup(
            ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(MakeReservationLabel)
                .addGap(19, 19, 19)
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeResFacLabel)
                    .addComponent(MakeResDateLabel)
                    .addComponent(MakeResAddSeatsLAbel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakeReservationButton)
                    .addComponent(ReservationSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationbyFacLabel)
                    .addComponent(ReservationsbyDateSearchLabel))
                .addGap(15, 15, 15)
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationsbyFacButton)
                    .addComponent(ReservationsbyFacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReservationsbyDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReservationsbyDateButton))
                .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(ResFeedbackLabel))
                    .addGroup(ReservationPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ReservationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddDatePanel.addTab("Reservation", ReservationPanel);

        ClearDataButton.setText("Clear Data");
        ClearDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(MainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddDatePanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ClearDataButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClearDataButton)
                .addGap(4, 4, 4)
                .addComponent(MainLabel)
                .addGap(36, 36, 36)
                .addComponent(AddDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFacultyButtonActionPerformed
        
        String name = addFacultyNameTextField.getText();
        addFacultyNameTextField.setText("");
        
        if (name != null)
        {
        Faculty.addFaculty(name);
        
        AddFacultyFeedbackLabel.setText(name+" has been added to the Faculty.");
        }
       
        
        ListFacTextArea.setText(DataTypeTools.ALtoPrintableString(Faculty.getFacultyList()));
        FacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));
        ReservationsbyFacComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));
    }//GEN-LAST:event_AddFacultyButtonActionPerformed

    private void AddRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomButtonActionPerformed
       
        String name = RoomNameTextField.getText();
        Integer seats = Integer.parseInt(SeatNumberTextField.getText());
        
        if (name != null)
        {
        RoomEntry.addRoom(name, seats);
        
        AddRoomFeedbackLabel.setText(name+" has been added to the Rooms.");
        }
        
        GetRoomsTextArea.setText(DataTypeTools.ALtoPrintableString(RoomEntry.getAllRooms()));
        DeleteRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(RoomEntry.getRoomStringArray()));
        
    }//GEN-LAST:event_AddRoomButtonActionPerformed

    private void AddDatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDatesButtonActionPerformed

        String userInput = AddDatesYearTextField.getText()+'-'+AddDatesMonthTextField.getText()+'-'+AddDatesDaysTextField.getText();
        
        Integer year=Integer.parseInt(AddDatesYearTextField.getText())-1900;
        Integer month=Integer.parseInt(AddDatesMonthTextField.getText())-1;
        Integer day=Integer.parseInt(AddDatesDaysTextField.getText());
        
        Date date = new Date(year,month,day); 
        Dates.addDates(date);
        
        AddDatesFeedbackLabel.setText(userInput+" has been added to the Dates.");
        
        
        ShowAllDatesTextArea.setText(Dates.AllDatesListString());
        
        DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));
        ReservationsbyDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));
    }//GEN-LAST:event_AddDatesButtonActionPerformed

    private void ClearDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDataButtonActionPerformed
        // TODO add your handling code here:
        connection = DBConnection.getConnection();
        
        try
        {
            Clear = connection.prepareStatement("Delete from Dates");
            Clear.executeUpdate();
            Clear = connection.prepareStatement("Delete from Faculty");
            Clear.executeUpdate();
            Clear = connection.prepareStatement("Delete from Reservations");
            Clear.executeUpdate();
            Clear = connection.prepareStatement("Delete from Rooms");
            Clear.executeUpdate();
            
            DateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));
            
            FacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));
            
            ReservationsbyFacComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Faculty.getFacStringArray()));
            
            ReservationsbyDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(Dates.getDatesStringArray()));
        }
        catch(SQLException sqlException)
        {
            sqlException.printStackTrace();
        }
        
    }//GEN-LAST:event_ClearDataButtonActionPerformed

    private void MakeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeReservationButtonActionPerformed
      String Faculty = FacultyComboBox.getSelectedItem().toString();
      String Date = DateComboBox.getSelectedItem().toString();
      Integer Seats= Integer.parseInt(ReservationSeatsTextField.getText());
      
      Reservation.addReservationEntry(Faculty, Date, Seats);
    }//GEN-LAST:event_MakeReservationButtonActionPerformed

    private void FacultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyComboBoxActionPerformed

    private void DeleteRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoomButtonActionPerformed
        
        String name = DeleteRoomComboBox.getSelectedItem().toString();
        
        RoomEntry.dropRoom(name);
        DeleteRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(RoomEntry.getRoomStringArray()));
        GetRoomsTextArea.setText(RoomEntry.AllRoomsListString());
        
    }//GEN-LAST:event_DeleteRoomButtonActionPerformed

    private void ReservationSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservationSeatsTextFieldActionPerformed

    private void ReservationsbyFacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationsbyFacButtonActionPerformed
        // TODO add your handling code here:
    String name= ReservationsbyFacComboBox.getSelectedItem().toString();
    ReservationTextArea.setText(DataTypeTools.PrintResultSet(ReservationQueries.getReservationsByFaculty(name)));
    
    }//GEN-LAST:event_ReservationsbyFacButtonActionPerformed

    private void ReservationsbyDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationsbyDateButtonActionPerformed
    String Date= ReservationsbyDateComboBox.getSelectedItem().toString();
    ReservationTextArea.setText(DataTypeTools.PrintResultSet(ReservationQueries.getReservationsByDate(Date)));
    }//GEN-LAST:event_ReservationsbyDateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AddDatePanel;
    private javax.swing.JButton AddDatesButton;
    private javax.swing.JTextField AddDatesDaysTextField;
    private javax.swing.JLabel AddDatesFeedbackLabel;
    private javax.swing.JLabel AddDatesJLabel;
    private javax.swing.JTextField AddDatesMonthTextField;
    private javax.swing.JPanel AddDatesPanel;
    private javax.swing.JTextField AddDatesYearTextField;
    private javax.swing.JButton AddFacultyButton;
    private javax.swing.JLabel AddFacultyFeedbackLabel;
    private javax.swing.JPanel AddFacultyPanel;
    private javax.swing.JButton AddRoomButton;
    private javax.swing.JLabel AddRoomFeedbackLabel;
    private javax.swing.JLabel AddRoomLabel;
    private javax.swing.JLabel AllDatesLabel;
    private javax.swing.JLabel AllRoomsLabel;
    private javax.swing.JButton ClearDataButton;
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JLabel DatesDayLabel;
    private javax.swing.JLabel DatesMonthLabel;
    private javax.swing.JLabel DatesYearLabel;
    private javax.swing.JButton DeleteRoomButton;
    private javax.swing.JComboBox<String> DeleteRoomComboBox;
    private javax.swing.JLabel DeleteRoomLabel;
    private javax.swing.JComboBox<String> FacultyComboBox;
    private javax.swing.JLabel FacultyListLabel;
    private javax.swing.JLabel FacultyNameLabel;
    private javax.swing.JScrollPane GetRoomsScrollPane;
    private javax.swing.JTextArea GetRoomsTextArea;
    private javax.swing.JTextArea ListFacTextArea;
    private javax.swing.JScrollPane ListFacultyScrollPane;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JLabel MakeResAddSeatsLAbel;
    private javax.swing.JLabel MakeResDateLabel;
    private javax.swing.JLabel MakeResFacLabel;
    private javax.swing.JButton MakeReservationButton;
    private javax.swing.JLabel MakeReservationLabel;
    private javax.swing.JLabel ResFeedbackLabel;
    private javax.swing.JPanel ReservationPanel;
    private javax.swing.JScrollPane ReservationScrollPane;
    private javax.swing.JTextField ReservationSeatsTextField;
    private javax.swing.JTextArea ReservationTextArea;
    private javax.swing.JLabel ReservationbyFacLabel;
    private javax.swing.JButton ReservationsbyDateButton;
    private javax.swing.JComboBox<String> ReservationsbyDateComboBox;
    private javax.swing.JLabel ReservationsbyDateSearchLabel;
    private javax.swing.JButton ReservationsbyFacButton;
    private javax.swing.JComboBox<String> ReservationsbyFacComboBox;
    private javax.swing.JPanel RoomEntryPanel;
    private javax.swing.JTextField RoomNameTextField;
    private javax.swing.JTextField SeatNumberTextField;
    private javax.swing.JScrollPane ShowAllDatesScrolllPane;
    private javax.swing.JTextArea ShowAllDatesTextArea;
    private javax.swing.JTextField addFacultyNameTextField;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
