
import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ianno
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        rebuildFacultyComboBoxes();
        rebuildDateComboBox();
        rebuildReservationByDateComboBox();
    }
    public void rebuildFacultyComboBoxes()
    {
        RRFacComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));       
    }
    public void rebuildDateComboBox(){
        RRDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }
    public void rebuildReservationByDateComboBox(){
        ResDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomSchedulerLabel = new javax.swing.JLabel();
        ReservationsPanel = new javax.swing.JTabbedPane();
        AddFacPanel = new javax.swing.JPanel();
        FacultyNameLabel = new javax.swing.JLabel();
        FacNameTextField = new javax.swing.JTextField();
        addFacButton = new javax.swing.JButton();
        addFacStatusLabel = new javax.swing.JLabel();
        ResereRoomPanel = new javax.swing.JPanel();
        RRFacultyLabel = new javax.swing.JLabel();
        RRFacComboBox = new javax.swing.JComboBox<>();
        RRDateLabel = new javax.swing.JLabel();
        RRDateComboBox = new javax.swing.JComboBox<>();
        RRSeatsLabel = new javax.swing.JLabel();
        RRSeatsTextField = new javax.swing.JTextField();
        RRSubmitButton = new javax.swing.JButton();
        RRFeedbackLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ResDateLabel = new javax.swing.JLabel();
        ResDateComboBox = new javax.swing.JComboBox<>();
        ResButton = new javax.swing.JButton();
        ResScrollPane = new javax.swing.JScrollPane();
        ResTextArea = new javax.swing.JTextArea();
        WaitlistPanel = new javax.swing.JPanel();
        WLScrollPanel = new javax.swing.JScrollPane();
        WLTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RoomSchedulerLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        RoomSchedulerLabel.setForeground(new java.awt.Color(255, 102, 102));
        RoomSchedulerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomSchedulerLabel.setText("Room Scheduler");

        FacultyNameLabel.setText("Faculty Name:");

        addFacButton.setText("Submit");
        addFacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddFacPanelLayout = new javax.swing.GroupLayout(AddFacPanel);
        AddFacPanel.setLayout(AddFacPanelLayout);
        AddFacPanelLayout.setHorizontalGroup(
            AddFacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacPanelLayout.createSequentialGroup()
                .addGroup(AddFacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddFacPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FacultyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FacNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddFacPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addFacStatusLabel))
                    .addGroup(AddFacPanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(addFacButton)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        AddFacPanelLayout.setVerticalGroup(
            AddFacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(AddFacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FacNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFacButton)
                .addGap(18, 18, 18)
                .addComponent(addFacStatusLabel)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        ReservationsPanel.addTab("Add Faculty", AddFacPanel);

        RRFacultyLabel.setText("Faculty:");

        RRFacComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        RRDateLabel.setText("Date:");

        RRDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        RRSeatsLabel.setText("Seats Required:");

        RRSubmitButton.setText("Submit");
        RRSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResereRoomPanelLayout = new javax.swing.GroupLayout(ResereRoomPanel);
        ResereRoomPanel.setLayout(ResereRoomPanelLayout);
        ResereRoomPanelLayout.setHorizontalGroup(
            ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResereRoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResereRoomPanelLayout.createSequentialGroup()
                        .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RRFacultyLabel)
                            .addComponent(RRDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ResereRoomPanelLayout.createSequentialGroup()
                                .addComponent(RRDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(RRSubmitButton))
                            .addComponent(RRFacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ResereRoomPanelLayout.createSequentialGroup()
                        .addComponent(RRSeatsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(RRSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RRFeedbackLabel))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        ResereRoomPanelLayout.setVerticalGroup(
            ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResereRoomPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRFacultyLabel)
                    .addComponent(RRFacComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRDateLabel)
                    .addComponent(RRDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RRSubmitButton))
                .addGap(66, 66, 66)
                .addGroup(ResereRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RRSeatsLabel)
                    .addComponent(RRSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(RRFeedbackLabel)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        ReservationsPanel.addTab("Reserve Room", ResereRoomPanel);

        ResDateLabel.setText("Date:");

        ResDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        ResButton.setText("Search");
        ResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResButtonActionPerformed(evt);
            }
        });

        ResTextArea.setColumns(20);
        ResTextArea.setRows(5);
        ResTextArea.setText("Status:\n\nReservation                  \tDate");
        ResScrollPane.setViewportView(ResTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResDateLabel)
                    .addComponent(ResDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ResScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(ResDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(ResButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReservationsPanel.addTab("Reservations", jPanel1);

        WLTextArea.setColumns(20);
        WLTextArea.setRows(5);
        WLTextArea.setText("Faculty              Seats                         Date ");
        WLScrollPanel.setViewportView(WLTextArea);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WaitlistPanelLayout = new javax.swing.GroupLayout(WaitlistPanel);
        WaitlistPanel.setLayout(WaitlistPanelLayout);
        WaitlistPanelLayout.setHorizontalGroup(
            WaitlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WLScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        WaitlistPanelLayout.setVerticalGroup(
            WaitlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WLScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(WaitlistPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReservationsPanel.addTab("Waitlist", WaitlistPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RoomSchedulerLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RoomSchedulerLabel)
                .addGap(18, 18, 18)
                .addComponent(ReservationsPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacButtonActionPerformed
        String name = FacNameTextField.getText();
        Faculty.addFaculty(name);
        addFacStatusLabel.setText(name+" has been added to the Faculty.");
        rebuildFacultyComboBoxes();
    }//GEN-LAST:event_addFacButtonActionPerformed

    private void RRSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRSubmitButtonActionPerformed
        String faculty = RRFacComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(RRDateComboBox.getSelectedItem().toString());
        int seats = Integer.parseInt(RRSeatsTextField.getText());
        Timestamp timestamp = new Timestamp(Calendar.getInstance().getTime().getTime());
        ArrayList <String> PossibleRooms = RoomQueries.getAllPossibleRooms(seats);
        ArrayList <String> reservedRooms = ReservationQueries.getRoomsReservedByDate(date);
        
        for (String room: PossibleRooms){
            if(!reservedRooms.contains(room)){
                ReservationQueries.addReservationEntry(faculty, room, seats,date, timestamp);
                RRFeedbackLabel.setText(" Room " + room + " has been reserved ");
                return;
                
            }
        }
        WaitListQueries.addWaitlistEntry(faculty, date, seats, timestamp);
            RRFeedbackLabel.setText("No rooms available, added to waitlist");
    }//GEN-LAST:event_RRSubmitButtonActionPerformed

    private void ResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResButtonActionPerformed
        Date date = Date.valueOf(ResDateComboBox.getSelectedItem().toString());
        ArrayList<ReservationEntry> RList = ReservationQueries.getReservationsByDate(date);
        for (ReservationEntry entry: RList)
        {
        ResTextArea.append("\n"+entry.getFaculty() + " reserved " + entry.getRooms()+  "\t" + "\t"   + entry.getDate() + "\n");    
        }
    }//GEN-LAST:event_ResButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date date = Date.valueOf(RRDateComboBox.getSelectedItem().toString());
        ArrayList<WaitListEntry> WList = WaitListQueries.getWaitlist();
        for (WaitListEntry entry: WList){
            WLTextArea.append("\n" +entry.getFaculty()+"\t"+ entry.getSeats()   + "\t"   + entry.getDate()+"\n");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddFacPanel;
    private javax.swing.JTextField FacNameTextField;
    private javax.swing.JLabel FacultyNameLabel;
    private javax.swing.JComboBox<String> RRDateComboBox;
    private javax.swing.JLabel RRDateLabel;
    private javax.swing.JComboBox<String> RRFacComboBox;
    private javax.swing.JLabel RRFacultyLabel;
    private javax.swing.JLabel RRFeedbackLabel;
    private javax.swing.JLabel RRSeatsLabel;
    private javax.swing.JTextField RRSeatsTextField;
    private javax.swing.JButton RRSubmitButton;
    private javax.swing.JButton ResButton;
    private javax.swing.JComboBox<String> ResDateComboBox;
    private javax.swing.JLabel ResDateLabel;
    private javax.swing.JScrollPane ResScrollPane;
    private javax.swing.JTextArea ResTextArea;
    private javax.swing.JPanel ResereRoomPanel;
    private javax.swing.JTabbedPane ReservationsPanel;
    private javax.swing.JLabel RoomSchedulerLabel;
    private javax.swing.JScrollPane WLScrollPanel;
    private javax.swing.JTextArea WLTextArea;
    private javax.swing.JPanel WaitlistPanel;
    private javax.swing.JButton addFacButton;
    private javax.swing.JLabel addFacStatusLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
